webtalk_init -webtalk_dir C:/Users/wuyesai/Desktop/duogongnengshuzizhong/duogongnengshuzizhong.sim/sim_1/behav/xsim/xsim.dir/top_clocksim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 16 23:38:07 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "49035f37cd7a57acbb2dc344a64d1e00" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f45075a3c3fc462e99d8b118b1fcca6f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "151 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7752_KB" -context "xsim\\usage"
webtalk_transmit -clientid 931745233 -regid "" -xml C:/Users/wuyesai/Desktop/duogongnengshuzizhong/duogongnengshuzizhong.sim/sim_1/behav/xsim/xsim.dir/top_clocksim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/wuyesai/Desktop/duogongnengshuzizhong/duogongnengshuzizhong.sim/sim_1/behav/xsim/xsim.dir/top_clocksim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/wuyesai/Desktop/duogongnengshuzizhong/duogongnengshuzizhong.sim/sim_1/behav/xsim/xsim.dir/top_clocksim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
